version: "3.9"
services:
  db:
    image: postgres:13.4-alpine3.14
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/setupdb.sh:/docker-entrypoint-initdb.d/setupdb.sh
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: "5s"
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: on-challenge
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
